# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# --------------------------=== pod 4 ===--------------------------
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbft-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pbft-4
  template:
    metadata:
      labels:
        app: pbft-4
    spec:
      containers:
        - name: sawtooth-intkey-tp-python
          image: hyperledger/sawtooth-intkey-tp-python:chime
          command:
            - bash
          args:
            - -c
            - "intkey-tp-python -vv -C tcp://$HOSTNAME:4004"

        - name: sawtooth-pbft-engine
          image: hyperledger/sawtooth-pbft-engine:chime
          command:
            - bash
          args:
            - -c
            - "pbft-engine -vv --connect tcp://$HOSTNAME:5050"

        - name: sawtooth-rest-api
          image: hyperledger/sawtooth-rest-api:chime
          ports:
            - name: api
              containerPort: 8008
          command:
            - bash
          args:
            - -c
            - "sawtooth-rest-api -vv -C tcp://$HOSTNAME:4004 -B 0.0.0.0:8008"
          readinessProbe:
            httpGet:
              path: /status
              port: 8008
            initialDelaySeconds: 15
            periodSeconds: 10

        - name: sawtooth-settings-tp
          image: hyperledger/sawtooth-settings-tp:chime
          command:
            - bash
          args:
            - -c
            - "settings-tp -vv -C tcp://$HOSTNAME:4004"

        - name: sawtooth-shell
          image: hyperledger/sawtooth-shell:chime
          command:
            - bash
          args:
            - -c
            - "sawtooth keygen && tail -f /dev/null"

        - name: sawtooth-smallbank-tp-rust
          image: hyperledger/sawtooth-smallbank-tp-rust:chime
          command:
            - bash
          args:
            - -c
            - "smallbank-tp-rust -vv -C tcp://$HOSTNAME:4004"

        - name: sawtooth-validator
          image: hyperledger/sawtooth-validator:chime
          ports:
            - name: tp
              containerPort: 4004
            - name: consensus
              containerPort: 5050
            - name: validators
              containerPort: 8800
          env:
            - name: pbft4priv
              valueFrom:
                configMapKeyRef:
                  name: keys-config
                  key: pbft4priv
            - name: pbft4pub
              valueFrom:
                configMapKeyRef:
                  name: keys-config
                  key: pbft4pub
          command:
            - bash
          args:
            - -c
            - |
                if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
                  echo $pbft4priv > /etc/sawtooth/keys/validator.priv
                  echo $pbft4pub > /etc/sawtooth/keys/validator.pub
                fi &&
                sawtooth keygen my_key &&
                sawtooth-validator -vv \
                  --endpoint tcp://$SAWTOOTH_4_SERVICE_HOST:8800 \
                  --bind component:tcp://0.0.0.0:4004 \
                  --bind consensus:tcp://0.0.0.0:5050 \
                  --bind network:tcp://0.0.0.0:8800 \
                  --scheduler parallel \
                  --peering static \
                  --maximum-peer-connectivity 10000 \
                  --peers tcp://$SAWTOOTH_0_SERVICE_HOST:8800 \
                  --peers tcp://$SAWTOOTH_1_SERVICE_HOST:8800 \
                  --peers tcp://$SAWTOOTH_2_SERVICE_HOST:8800 \
                  --peers tcp://$SAWTOOTH_3_SERVICE_HOST:8800

        - name: sawtooth-xo-tp-python
          image: hyperledger/sawtooth-xo-tp-python:chime
          command:
            - bash
          args:
            - -c
            - "xo-tp-python -vv -C tcp://$HOSTNAME:4004"
