name: conensource
ledger: sawtooth
version: chime
consensus: pbft
nodes: 5
orchestration: kubernetes # why would we use anything else?
processors:
  - name: consensource-tp
    image: target/consensource-processor:latest
subscribers:
  - name: consensource-sds
    image: target/consensource-sds:latest